"""
finalize_concordance.py

Takes the reviewed concordance draft (after manual review of validation_report.csv)
and produces the final, locked concordance_v1.csv with all rows marked verified=true.

Usage:
    python code/src/mapping/finalize_concordance.py \
        --input data/02_ground_truth/concordance_v1_draft.csv \
        --output data/02_ground_truth/concordance_v1.csv
"""

import os
import csv
import argparse
import logging
from datetime import date

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)
log = logging.getLogger("finalize_concordance")


def finalize(input_path, output_path):
    """
    Read the draft concordance, mark all rows verified, and write final version.
    Also performs final sanity checks.
    """
    if not os.path.exists(input_path):
        log.error(f"Input not found: {input_path}")
        return False

    rows = []
    with open(input_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        for row in reader:
            row["verified"] = "true"
            row["last_updated"] = date.today().isoformat()
            rows.append(row)

    # Sanity checks
    ipc_sections_seen = set()
    issues = 0
    for row in rows:
        ipc = row.get("ipc_section", "").strip()
        rel = row.get("relationship_type", "").strip()
        notes = row.get("notes", "").strip()

        # Check: ambiguous types should have notes
        if rel in ("split", "merged", "repealed", "modified") and not notes:
            log.warning(f"IPC {ipc}: '{rel}' without notes — add explanation")
            issues += 1

        if ipc:
            if ipc in ipc_sections_seen:
                log.warning(f"IPC {ipc}: duplicate entry")
                issues += 1
            ipc_sections_seen.add(ipc)

    log.info(f"Rows: {len(rows)}, Issues: {issues}")

    # Write final
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    log.info(f"Final concordance written to: {output_path}")
    log.info(f"IMPORTANT: Do not edit this file directly. To make corrections,")
    log.info(f"  bump version to concordance_v2.csv and log changes in CHANGELOG.md")

    return True


def main():
    parser = argparse.ArgumentParser(description="Finalize concordance table")
    root = os.environ.get("IPC2BNS_PROJECT_ROOT", "/content/drive/MyDrive/NLP_rspaper")
    parser.add_argument("--input", default=os.path.join(root, "data/02_ground_truth/concordance_v1.csv"))
    parser.add_argument("--output", default=os.path.join(root, "data/02_ground_truth/concordance_v1.csv"))
    args = parser.parse_args()
    finalize(args.input, args.output)


if __name__ == "__main__":
    main()
